# Generated by Django 5.2.3 on 2025-07-14 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='userprofile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('Offer', 'Offer'), ('Request', 'Request')], default='Offer', max_length=20)),
                ('avaliability', models.CharField(max_length=250)),
                ('pitch', models.CharField(max_length=140)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_skillswap_app.userprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_skillswap_app.skill')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(through='dj_skillswap_app.UserProfileSkill', to='dj_skillswap_app.skill'),
        ),
    ]
