# Generated by Django 5.2.3 on 2025-07-14 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileskill',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofileskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
