# Generated by Django 5.2.4 on 2025-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0002_message_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileskill',
            name='avaliability',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Weekends only', 'Weekends only'), ('On request', 'On request'), ('Flexible', 'Flexible')], default='Full-time', max_length=30),
        ),
    ]
