# Generated by Django 5.2.3 on 2025-07-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilekill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('REQUEST', 'Request')], default='OFFER', max_length=20)),
                ('avaliabilitty', models.CharField(max_length=250)),
                ('pitch', models.CharField(max_length=140)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_skillswap_app.profile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_skillswap_app.skill')),
            ],
        ),
    ]
