# Generated by Django 5.2.4 on 2025-07-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0003_alter_userprofileskill_avaliability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 'Five'), (4, 'Four'), (3, 'Three'), (2, 'Two'), (1, 'One'), (0, 'None')])),
                ('comment', models.TextField()),
                ('rating_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_receiver', to='dj_skillswap_app.userprofile')),
                ('rating_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_sender', to='dj_skillswap_app.userprofile')),
            ],
        ),
    ]
