# Generated by Django 5.2.4 on 2025-07-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills_needed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_offered',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
