# Generated by Django 5.2.3 on 2025-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0003_profilekill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilekill',
            new_name='ProfileSkill',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(through='dj_skillswap_app.ProfileSkill', to='dj_skillswap_app.skill'),
        ),
    ]
