# Generated by Django 5.2.3 on 2025-07-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_skillswap_app', '0004_rename_profilekill_profileskill_profile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileskill',
            old_name='avaliabilitty',
            new_name='avaliability',
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='type',
            field=models.CharField(choices=[('Offer', 'Offer'), ('Request', 'Request')], default='Offer', max_length=20),
        ),
    ]
